### ISSUE TITLE
Bug in timeline when using custom start/end date in cyclic temporal composition

### ISSUE THREAD

**Issue by raphaelrpl** [brazil-data-cube/cube-builder#108]
When i trigger any data cube which has a cyclic temporal composition yealy, the timeline does not fit properly. 

For example:
start_date=2016-08-01
end_date=2020-05-31

The last timeline should be `2020-05-23`, which represents the period `2020-05-08 to 2020-05-23`, however a new period is created `2020-05-24 to 2020-05-31`.

**Comment by betonr** [comment]
will always generate an extra period at the end
