### ISSUE TITLE
Add Support to Histogram Equalization (Matching)

### ISSUE THREAD

**Issue by marujore** [brazil-data-cube/cube-builder#138]
Allow optional Histogram Equalization (Matching) after merge and before (or during) blend.
This will use the most clear image (sorted by cloud cover) as referente and match each other merged image histogram to it.

scikit-image provides the histogram matching function: https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_histogram_matching.html

**Comment by raphaelrpl** [comment]
Resolved in PR #148
