### ISSUE TITLE
README.rst: broken link to read the docs

### ISSUE THREAD

**Issue by jakimowb** [brazil-data-cube/cube-builder#174]
The README.rst contains a broken link to https://cube-builder.readthedocs.io/en/latest/ 
Where can I find the RTD documentation instead?

**Comment by raphaelrpl** [comment]
Hi @jakimowb,

Many thanks for the contact.

We were having build problem with ReadTheDocs. Now it's fixed. :smile:
Sorry for any inconvenience.

Please, feel free to collaborate, opening issues, etc.

Thanks again.

**Comment by jakimowb** [comment]
Great, thanks for solving this so quick @raphaelrpl .
