### ISSUE TITLE
Could not deploy cube-builder using docker-compose.yml - lack of postgres container section no DEPLOY.rst

### ISSUE THREAD

**Issue by mariem940** [brazil-data-cube/cube-builder#190]
i have a problem in the docker-compose.yml, when i execute this command "docker-compose up -d postgres" , a message is displayed indicating that there is no postgres service, how to solve this problem and thanks.

**Comment by raphaelrpl** [comment]
Hi @mariem940,

Thanks for reporting this bug. It will be fixed next patch 0.6.3 (next week).
For now, consider to have a running PostgreSQL with PostGIS support. You may use this docker image [postgis/postgis:13-3.1](https://hub.docker.com/r/postgis/postgis) and make sure to run `./deploy/configure-db.sh` to prepare the Database System as described in the document [`INSTALL.rst`](https://github.com/brazil-data-cube/cube-builder/blob/master/INSTALL.rst#prepare-the-database-system).

Best,
Raphael.
