### ISSUE TITLE
Infinite loop when generating timeline with single interval

### ISSUE THREAD

**Issue by raphaelrpl** [brazil-data-cube/cube-builder#97]
Based in commit 2f6fd3d, we can generate data cube using custom intervals in year (i.e seasons)

However, when we send only two intervals, it seems to be stuck in infinite loop in the line [timeline.py L101](https://github.com/brazil-data-cube/cube-builder/blob/master/cube_builder/utils/timeline.py#L101).

Steps to reproduce:
Use the following `temporal_schema` while creating a new data cube definition:

```json
{
  "temporal_schema": {
    "schema": "Continuous",
    "step": 3,
    "unit": "month",
    "intervals": [
        "03-21_06-20"
    ]
  }
}
```

**Comment by betonr** [comment]
resolved in https://github.com/brazil-data-cube/cube-builder/pull/101
